name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: templates
    type: git
    name: pipeline-templates/pipeline-templates
    ref: main

trigger: none

extends:
  template: start.yml@templates
  parameters:
    language: 'dotnet'
    poolName: 'windows-latest'
    testProject: '**\$(BuildConfiguration)\FabrikamFiber.Web.Tests.dll'
    #environments:
    # - name: 'dev'
    #   target: 'azure-webapp'
    #   depends: 'build'
    # - name: 'qa'
    #   target: 'azure-webapp'
    #   depends: 'dev'
    # - name: 'prd'
    #   target: 'azure-webapp'
    #   depends: 'qa'