name: Build, Test and Deploy

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

env:
  rgName: rg-fabrikamfiber-qa
  location: centralus
  appName: app-fabrikamfiber-qa
  planName: asp-fabrikamfiber
  sqlserverName: sql-fabrikamfiber
  sqldbName: db-fabrikamfiber

jobs:
  iac:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
      
      - name: Check and Create Resource Group
        run: |
          $rgExists = az group exists --name ${{ env.rgName }}

          if ($rgExists -eq 'true') 
          {
            Write-Output "Resource group ${{ env.rgName }} already exists."
          } 
          else 
          {
            Write-Output "Resource group ${{ env.rgName }} does not exist. Creating..."
            az group create --name ${{ env.rgName }} --location ${{ env.location }}
          }

      - name: Create Service Plan
        run: |
          Write-Output "Creating Service plan..."
          az appservice plan create --name ${{ env.planName }} --resource-group ${{ env.rgName }} --sku B1

          Write-Output "Creating Web App..."
          az webapp create --name ${{ env.appName }} --plan ${{ env.planName }} --resource-group  ${{ env.rgName }} --runtime ASPNET:V4.8

          Write-Output "Creating $server in $location..."
          az sql server create --name ${{ env.sqlserverName }} --resource-group ${{ env.rgName }} --location ${{ env.location }} --admin-user "fabrikamfiber-sql" --admin-password "#P@ssw0rd2025#"
          
          Write-Output "Creating $database on $server..."
          az sql db create --resource-group ${{ env.rgName }} --server ${{ env.sqlserverName }} --name ${{ env.sqldbName }}


      #- name: Deploy Infrastructure using Bicep
      #  run: |
      #    az deployment group create --resource-group ${{ env.rgName }} --template-file FabrikamFiber.IAC/main.bicep --parameters webAppName=${{ env.appName }}

  build:
    needs: iac
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore FabrikamFiber.CallCenter.sln

      - name: Build Solution
        run: msbuild FabrikamFiber.CallCenter.sln /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:OutDir="${{ github.workspace }}\WebDeploy"

      - name: Run Tests
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "${{ github.workspace }}\WebDeploy\FabrikamFiber.Web.Tests.dll" /TestCaseFilter:"TestCategory=Required" /EnableCodeCoverage
      
      - name: Zip Published Website
        run: |
          Compress-Archive -Path "${{ github.workspace }}\WebDeploy\_PublishedWebsites\FabrikamFiber.Web\*" -DestinationPath "${{ github.workspace }}\WebDeploy\_PublishedWebsites\FabrikamFiber.Web.zip"

      - name: Archive WebDeploy
        uses: actions/upload-artifact@v4
        with:
          name: _PublishedWebsites
          path: ${{ github.workspace }}\WebDeploy\_PublishedWebsites\FabrikamFiber.Web.zip

      - name: Archive DacPac
        uses: actions/upload-artifact@v4
        with:
          name: DacPac
          path: ${{ github.workspace }}\WebDeploy\*.dacpac

  deploy_qa:
    needs: build
    runs-on: windows-latest
    environment: QA
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: View files
        run: |
          ls -R

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
      
      - name: Install SqlPackage
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/sqlpackage-windows" -OutFile "sqlpackage.zip"
          Expand-Archive -Path "sqlpackage.zip" -DestinationPath "${{ github.workspace }}\sqlpackage"

      - name: Deploy DacPac to Azure SQL
        run: |
          & "${{ github.workspace }}\sqlpackage\SqlPackage.exe" /Action:Publish /SourceFile:"${{ github.workspace }}\DacPac\FabrikamFiber.Database.dacpac" /TargetConnectionString:"${{ secrets.DB_CONNECTION_STRING }}"

      - name: Deploy APP
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: ${{ env.rgName }}
          app-name: ${{ env.appName }}
          package: "_PublishedWebsites/FabrikamFiber.Web.zip"