name: Build, Test and Deploy

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore FabrikamFiber.CallCenter.sln

      #- name: Build Solution
      #  run: msbuild FabrikamFiber.CallCenter.sln /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{ github.workspace }}\WebDeploy" /p:AutoParameterizationWebConfigConnectionStrings=false

      - name: Build Solution
        run: msbuild FabrikamFiber.CallCenter.sln /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:OutDir="${{ github.workspace }}\WebDeploy"

      - name: Run Tests
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "${{ github.workspace }}\WebDeploy\FabrikamFiber.Web.Tests.dll" /TestCaseFilter:"TestCategory=Required" /EnableCodeCoverage
      
      - name: Archive WebDeploy
        uses: actions/upload-artifact@v4
        with:
          name: WebApp
          path: ${{ github.workspace }}\WebDeploy

      - name: Archive DACPAC
        uses: actions/upload-artifact@v4
        with:
          name: DacPac
          path: '**/FabrikamFiber.Database/bin/Release/*.dacpac'

      - name: Archive Selenium Content
        uses: actions/upload-artifact@v4
        with:
          name: Selenium
          path: |
            **/FabrikamFiber.Web.PureSeleniumTests/bin/Release/**
            **/*.testsettings
            **/*.runsettings

  deploy_qa:
    needs: build
    runs-on: windows-latest
    environment: QA
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: View files
        run: |
          ls -R

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
      
      - name: Deploy APP
        uses: azure/webapps-deploy@v3
        with:
          resource-group-name: rg-fabrikamfiber-qa
          app-name: app-fabrikamfiber-qa
          package: "WebApp"

  deploy_prod:
    needs: deploy_qa
    runs-on: windows-latest
    environment: PROD
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: View files
        run: |
          ls -R

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.ORG_AZ_CREDENTIALS }}
      
      #- name: Deploy APP
      #  uses: azure/webapps-deploy@v3
      #  with:
      #    resource-group-name: rg-fabrikamfiber-qa
      #    app-name: app-fabrikamfiber-qa
      #    package: "WebApp"