name: Testes

on:
  workflow_dispatch:

env:
  rgName: rg-fabrikamfiber-qa
  location: centralus
  appName: app-fabrikamfiber-qa
  planName: asp-fabrikamfiber
  sqlserverName: sql-fabrikamfiber
  sqldbName: db-fabrikamfiber

jobs:
  teste1:
    runs-on: windows-latest
    steps:
      - name: Create Connection String
        run: |
          echo "DB_CONNECTION_STRING=Server" >> $GITHUB_ENV

      - name: View SQL Connection String
        run: |
          Write-Output "SQL Connection String 1 = ${{ env.DB_CONNECTION_STRING }}"
          Write-Output "SQL Connection String 2 = $DB_CONNECTION_STRING"
  teste2:
    runs-on: linux-latest
    steps:
      - name: Create Connection String
        run: |
          echo "DB_CONNECTION_STRING=Server" >> $GITHUB_ENV

      - name: View SQL Connection String
        run: |
          Write-Output "SQL Connection String 1 = ${{ env.DB_CONNECTION_STRING }}"
          Write-Output "SQL Connection String 2 = $DB_CONNECTION_STRING"