name: Testes

on:
  workflow_dispatch:

env:
  rgName: rg-fabrikamfiber-qa
  location: centralus
  appName: app-fabrikamfiber-qa
  planName: asp-fabrikamfiber
  sqlserverName: sql-fabrikamfiber
  sqldbName: db-fabrikamfiber

jobs:
  teste-win:
    runs-on: windows-latest
    steps:
      - name: Create Connection String
        run: |
          $connectionString = "Server"
          Write-Output "DB_CONNECTION_STRING=$connectionString" >> $GITHUB_ENV

      - name: View SQL Connection String
        run: |
          Write-Output "SQL Connection String 1 = ${{ env.DB_CONNECTION_STRING }}"
          Write-Output "SQL Connection String 2 = $DB_CONNECTION_STRING"
  teste-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Connection String
        run: |
          echo "DB_CONNECTION_STRING='Server=tcp:${{ env.sqlserverName }}.database.windows.net,1433;Initial Catalog=${{ env.sqldbName }};Persist Security Info=False;User ID=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'" >> $GITHUB_ENV

      - name: View SQL Connection String
        run: |
          echo "SQL Connection String 1 = ${{ env.DB_CONNECTION_STRING }}"
          echo "SQL Connection String 2 = $DB_CONNECTION_STRING"